### ISSUE TITLE
Windwalker\Router\Exception\RouteNotFoundException bug

### ISSUE THREAD

**Issue by supergud** [lyrasoft/luna#17]
Infinity loop in exception handler. Exception: exception 'LogicException' with message 'Please call this method after routing.' in /var/www/html/dvs/vendor/lyrasoft/luna/src/LunaPackage.php:135

如果沒有此router不會報404

![20160901-151930](https://cloud.githubusercontent.com/assets/3166468/18158713/8a0b8dd2-7057-11e6-87c1-8689efc333ee.png)

**Comment by asika32764** [comment]
版本是?

**Comment by asika32764** [comment]
Should be fixed in recent version
