### ISSUE TITLE
Duplicate function not working

### ISSUE THREAD

**Issue by EricTsao** [lyrasoft/luna#20]
Admin -> 點選任意項目後按duplicate

<img width="820" alt="category_manager__article_ _acti_-_amy__3_5_5_" src="https://cloud.githubusercontent.com/assets/2383506/19185561/bd807208-8cb4-11e6-9304-0c505179ac65.png">

<img width="966" alt="whoops__there_was_an_error__ _acti_-_amy__3_5_5_" src="https://cloud.githubusercontent.com/assets/2383506/19185591/df31f426-8cb4-11e6-9bc4-7fa519a76d34.png">

**Comment by asika32764** [comment]
每一頁都會這樣嗎？

**Comment by asika32764** [comment]
Fixed with https://github.com/ventoviro/phoenix/commit/fa7e43c0e3aeda7d4a3b17d6ff98af4c2db30e95
