### ISSUE TITLE
Categoey 儲存後 path 與 tree 沒有重建

### ISSUE THREAD

**Issue by chokeslam** [lyrasoft/luna#202]
<img width="1077" alt="localhost___127_0_0_1___addmaker___categories___phpMyAdmin_4_8_5" src="https://user-images.githubusercontent.com/34531644/74412621-d08a7b80-4e78-11ea-80da-874532bd5118.png">

<img width="1305" alt="__分類編輯____開發階段____" src="https://user-images.githubusercontent.com/34531644/74412666-e5ffa580-4e78-11ea-80a2-f6372102a26d.png">

<img width="1117" alt="localhost___127_0_0_1___addmaker___categories___phpMyAdmin_4_8_5" src="https://user-images.githubusercontent.com/34531644/74412711-029bdd80-4e79-11ea-9ac4-27cd9a1e173b.png">

如上圖 選擇上層後儲存 path 應該重建為 drar/idea , lft 及 rgt 也要重新做排序,但無動作.

**Comment by asika32764** [comment]
Fix in phoenix https://github.com/ventoviro/phoenix/commit/d49c22d6875508926b051995b2b3d8421befac09
