### ISSUE TITLE
後台修改廠商的相簿資訊時，會整個當掉，動不了 （addmaker 的問題）

### ISSUE THREAD

**Issue by yinminc** [lyrasoft/luna#241]
as title.

https://trello.com/c/Kt76mmfv/106-%E5%BE%8C%E5%8F%B0%E4%BF%AE%E6%94%B9%E5%BB%A0%E5%95%86%E7%9A%84%E7%9B%B8%E7%B0%BF%E8%B3%87%E8%A8%8A%E6%99%82%EF%BC%8C%E6%9C%83%E6%95%B4%E5%80%8B%E7%95%B6%E6%8E%89%EF%BC%8C%E5%8B%95%E4%B8%8D%E4%BA%86
![image](https://user-images.githubusercontent.com/28665511/106596265-b9fc9900-658f-11eb-849f-5a6e6c06f5c2.png)

**Comment by asika32764** [comment]
4947d608374659c3b57a2ec60fc4e392dbb93254
