### ISSUE TITLE
Page title trans id was wrong when unicorn view-edit and view-grid generate view file

### ISSUE THREAD

**Issue by yinminc** [lyrasoft/luna#299]
as title.

![截圖 2021-10-22 下午3 49 03](https://user-images.githubusercontent.com/28665511/138415580-95cc06ce-59eb-494f-ad87-b8945a30d2ce.png)

![截圖 2021-10-22 下午3 48 54](https://user-images.githubusercontent.com/28665511/138415567-d8815e78-e352-4e6a-bf69-4464741cdf77.png)

**Comment by asika32764** [comment]
Fix https://github.com/windwalker-io/unicorn/commit/98d1d46d1e7939b9f36d700a72a6f52b530c7cb5
