### ISSUE TITLE
field validate fail and rebuild tree success translate

### ISSUE THREAD

**Issue by yinminc** [lyrasoft/luna#335]
![screenshot 2022-02-20 下午2 56 21](https://user-images.githubusercontent.com/100744265/157606076-77033a4c-6b1b-4b9d-995d-0473a9044736.jpg)
![screenshot 2022-02-20 下午2 56 21](https://user-images.githubusercontent.com/100744265/156958294-c9e695a0-1dc0-43d9-a663-d1a29d6cf3df.jpg)
![screenshot 2022-02-20 下午2 56 21](https://user-images.githubusercontent.com/29626541/154832140-e1c7d73b-d83b-45c5-87ef-b61801ee747c.jpg)

**Comment by asika32764** [comment]
![screenshot 2022-04-09 下午4 38 13](https://user-images.githubusercontent.com/1639206/162563973-1f11db35-c530-4b1c-a387-e0bbe44aacf5.jpg)
![screenshot 2022-04-09 下午4 39 28](https://user-images.githubusercontent.com/1639206/162563975-906df4b2-be68-4d8c-b46b-0f1ec78a0d31.jpg)
