### ISSUE TITLE
Social Login User 重複建立

### ISSUE THREAD

**Issue by chokeslam** [lyrasoft/luna#344]
來源是工具兔, 下圖匡列的兩個帳號看起來都是從 facebook 進來的,卻重複建立了帳號

<img width="1396" alt="User編輯" src="https://user-images.githubusercontent.com/34531644/166428005-580f105c-07cb-4587-bb98-2f97a7c7712f.png">

(hide)

**Comment by asika32764** [comment]
我無法重現，除了這個案例外其他人還會出現嗎?

**Comment by asika32764** [comment]
應該修在這裡了 85d7538edcd42f44da1553259a589673bc0582b7
