### ISSUE TITLE
[page] TinyMCE linking can't edit cause bootstrap  

### ISSUE THREAD

**Issue by tony-hsueh** [lyrasoft/luna#416]
TinyMCE 於後台頁面管理中的編輯器內無法建立超連結文字
附圖連結：https://www.tiny.cloud/docs/integrations/bootstrap/#usingtinymceinabootstrapdialog
解決方式如下圖所示：

![截圖 2022-11-08 上午10 57 12](https://user-images.githubusercontent.com/95395228/200464926-28da32a5-d41f-4aea-b9f5-7172eff5aa1e.png)

**Comment by asika32764** [comment]
Fixed
